### ISSUE TITLE
 Apache HTTPD auto-instrumentation docker image for arm64 mismatch arch

### ISSUE THREAD

**Issue by fdiskbrain** [open-telemetry/opentelemetry-operator#1724] opened 2023-05-09 07:09 UTC
Apache HTTPD auto-instrumentation docker image for arm64 build with Apache HTTPD x64 libs. 
In build dockerfile [L12-15](https://github.com/open-telemetry/opentelemetry-operator/blob/main/autoinstrumentation/apache-httpd/Dockerfile#L12-L15)

```

...
RUN wget https://github.com/open-telemetry/opentelemetry-cpp-contrib/releases/download/webserver%2Fv$version/opentelemetry-webserver-sdk-x64-linux.tgz.zip
RUN unzip opentelemetry-webserver-sdk-x64-linux.tgz.zip
RUN mkdir agent
RUN tar -xvf opentelemetry-webserver-sdk-x64-linux.tgz -C agent
...
```

The action build and push arm64 images
```
....
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: autoinstrumentation/apache-httpd
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' }}
          build-args: version=${{ env.VERSION }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
...
```
https://github.com/open-telemetry/opentelemetry-operator/blob/main/.github/workflows/publish-autoinstrumentation-apache-httpd.yaml#L59

**Comment by jaronoff97** [comment] 2023-11-28 22:35
@chrlic  any chance you could look in to this? we're not pulling the correct webserver in the dockerfile

**Comment by pavolloffay** [comment] 2024-10-17 13:30
The instrumentation is released only for x64-linux https://github.com/open-telemetry/opentelemetry-cpp-contrib/releases it needs to be fixed first

**Comment by pavolloffay** [comment] 2024-10-17 13:32
duplicate of https://github.com/open-telemetry/opentelemetry-operator/issues/2469

**Closed by pavolloffay** 2024-10-17 13:32 UTC
Labels: auto-instrumentation:apache-httpd
