### ISSUE TITLE
Sigv4 Extension configuration failure for prometheusremotewrite

### ISSUE THREAD

**Issue by jacobwalters** [open-telemetry/opentelemetry-operator#1007] opened 2022-07-26 21:01 UTC
I am using the opentelemetryoperator version v0.54.0. I am attempting to configure a prometheus collector that will push metrics to Amazon Managed Prometheus. I am trying to use the mechanism of the sigv4 extension with the prometheusremotewrite as described in this document. 

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/sigv4authextension/README.md

The collector pod has this error in the logs

```
2022/07/26 20:12:00 AWS OTel Collector version: v0.19.0
2022/07/26 20:12:00 found no extra config, skip it, err: open /opt/aws/aws-otel-collector/etc/extracfg.txt: no such file or directory
Error: failed to get config: invalid configuration: extension "sigv4auth" has invalid configuration: bad AWS credentials
2022/07/26 20:12:00 application run finished with error: failed to get config: invalid configuration: extension "sigv4auth" has invalid configuration: bad AWS credentials
```

**Comment by pavolloffay** [comment] 2022-07-28 09:49
@jacobwalters is this related to collector or target allocator? 

For a better understanding of the issue could you please share the full CR?

**Comment by bryan-aguilar** [comment] 2022-08-19 16:53
We have seen this error before when [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) is not properly setup. Docs [here](https://aws-otel.github.io/docs/getting-started/adot-eks-add-on/installation#use-your-iam-role-to-launch-the-adot-collector) should point you in the correct direction.

**Comment by ThaiDangFr** [comment] 2022-09-09 14:55
same error here, and I'm sure IRSA is correctly configured as it works when EKS and AMP are in the same account
with different accounts, when I use the assume_role parameter, I end with the bad AWS credentials error

**Comment by bryan-aguilar** [comment] 2022-09-09 15:29
@jacobwalters @ThaiDangFr can you please share the collector configurations you were using?

**Comment by ThaiDangFr** [comment] 2022-09-12 08:43
finally issue solved for me this week end, the trust policy was not set properly

**Comment by jaronoff97** [comment] 2023-11-28 22:00
Closing this as it seems the issue is solved, please let me know if that's not the case.

**Closed by jaronoff97** 2023-11-28 22:00 UTC
Labels: area:collector
