### ISSUE TITLE
Use application hosted in OTEL org for e2e test cases

### ISSUE THREAD

**Issue by avadhut123pisal** [open-telemetry/opentelemetry-operator#1155] opened 2022-10-10 14:10 UTC
In e2e test cases for auto-instrumentation of all the languages, the application docker images used are from personal repositories.
Ideally, these e2e test cases should consume the application images hosted in OTEL org. 

_Originally posted by_ @Kielek in https://github.com/open-telemetry/opentelemetry-operator/pull/1151#discussion_r990950801

**Comment by jaronoff97** [comment] 2023-11-28 22:11
this is closed by #2222 and a dupe of https://github.com/open-telemetry/opentelemetry-operator/issues/2073

**Closed by jaronoff97** 2023-11-28 22:11 UTC
Labels: area:auto-instrumentation, auto-instrumentation:dotnet
