### ISSUE TITLE
OTEL_RESOURCE_ATTRIBUTES not loaded from configmap

### ISSUE THREAD

**Issue by dariusj1** [open-telemetry/opentelemetry-operator#3419] opened 2024-11-04 14:47 UTC
### Component(s)

auto-instrumentation

## Description

According to https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/agent-features.md 

> Environment variable configuration as per [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/sdk-environment-variables.md)

It indeed works, but only if I specify those envs in the `.spec.container[*].env` block as inline environments.

HOWEVER, it doesn't seem to be working if I configure my pod manifest to load environments from a configmap. In that case, the operator sets the env in pod manifest level completely ignoring the envs in configmap. 

This is the case with environment variables that operator sets itself, e.g. **OTEL_RESOURCE_ATTRIBUTES**.

## Expected Result
I'd expect the operator to acocunt for env vars loaded from external resources too, i.e. secrets and configmaps

## Actual Result
operator ignores OTEL_RESOURCE_ATTRIBUTES defined in configmap. But it does work as expected if I export this env directly in pod's manifest.

### Kubernetes Version

v1.30.4-eks-a737599

### Operator version

0.72.0

### Collector version

N/A

**Comment by jaronoff97** [comment] 2024-11-04 16:23
this is a duplicate of what is discussed in [this issue](https://github.com/open-telemetry/opentelemetry-operator/issues/3392) and i am going to close this in favor of that one. TL;DR: this would require us to get permissions to peak into arbitrary configmaps (and secrets) which is something we're wary of doing.

**Closed by jaronoff97** 2024-11-04 16:23 UTC
Labels: bug, needs triage
