### ISSUE TITLE
Collector update with sidecar mode is not rollout

### ISSUE THREAD

**Issue by maxime-menard** [open-telemetry/opentelemetry-operator#2078] opened 2023-09-01 15:52 UTC
I created a resource OpenTelemetryCollector with sidecar mode :

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: my-collector
spec:
  mode: sidecar
```

and I added the relevant annotation to the Deployment of my app :
```
spec:
  template:
    metadata:
      annotations:
        sidecar.opentelemetry.io/inject: "my-collector"
```

This is working perfectly, but if I do any change on the CR `my-collector`, I don't see the sidecar restarting automatically to pickup the change. If I recreate the pod, I can see that the sidecar is using the latest configuration from "my-collector".

I don't have the same issue if I am using a collector with deployment mode for example, as I can see the pod related to the collector restarting automatically with latest configuration.

**Comment by frzifus** [comment] 2023-09-12 11:32
hi @maxime-menard, thanks for reporting! But the collector is not restarting by design. Its up to you to restart your workload.

See:
- https://github.com/open-telemetry/opentelemetry-operator/issues/553

Closing it, since it seems to me like a duplicate. :+1:

**Closed by frzifus** 2023-09-12 11:32 UTC
Labels: area:collector

**Comment by maxime-menard** [comment] 2023-09-13 17:28
Hi @frzifus , so it is by design that the collector can restart in deployment mode, but not in sidecar mode ? Why is that related to the instrumention CR issue ?
