### ISSUE TITLE
OpenTelemetryCollector CRD configMap for collector's configuration purposes

### ISSUE THREAD

**Issue by sfc-gh-akrishnan** [open-telemetry/opentelemetry-operator#2135] opened 2023-09-19 23:33 UTC
Does OpenTelemetryCollector CRD allow for a configMap that can be mounted for collector's configuration purposes? If so, is there any example?

**Comment by pavolloffay** [comment] 2023-09-20 13:48
No, the collector config has to be inlined in the CR 

```yaml
spec:
  mode: deployment
  config: | 
```

**Comment by pavolloffay** [comment] 2023-09-20 13:54
duplicate of https://github.com/open-telemetry/opentelemetry-operator/issues/1089

**Closed by pavolloffay** 2023-09-20 13:54 UTC
