### ISSUE TITLE
Option to exclude certain ENV variables from auto-instrumentation

### ISSUE THREAD

**Issue by dkPranav** [open-telemetry/opentelemetry-operator#3462] opened 2024-11-15 08:16 UTC
### Component(s)

auto-instrumentation

### Is your feature request related to a problem? Please describe.

We are setting OTEL_SERVICE_NAME in the container image Dockerfile across many deployments.
We don't want the auto-instrumentation to inject this OTEL_SERVICE_NAME, so is there a way exclude injection of certain Env variables.

### Describe the solution you'd like

I believe these are the default ENVs injected when instrumentation.opentelemetry.io/inject-sdk annotation is added to a PodSpec,

```
OTEL_NODE_IP
OTEL_POD_IP
OTEL_SERVICE_NAME 
OTEL_RESOURCE_ATTRIBUTES_POD_NAME
OTEL_RESOURCE_ATTRIBUTES_NODE_NAME
OTEL_RESOURCE_ATTRIBUTES
```

Is there a way to exclude injection of them using the Intrumentation CR.

### Describe alternatives you've considered

I understand that we can explicitly pass these ENVs in the pod directly to override the default values. and also add an annotation to add custom attributes.

**Comment by jaronoff97** [comment] 2024-11-23 14:51
duplicate of #3464 i believe, closing in favor of that one.

**Closed by jaronoff97** 2024-11-23 14:51 UTC
Labels: enhancement, needs triage
