### ISSUE TITLE
Sidecar injection multiple namespace for one OpenTelemetryCollector CRD

### ISSUE THREAD

**Issue by anh-oolio** [open-telemetry/opentelemetry-operator#1296] opened 2022-12-01 12:03 UTC
I have just moved from using Jaeger Agent sidecar to OpenTelemetry Collector sidecar recently. I wonder if there is any way to use just only one OpenTelemetryCollector configuration to inject sidecar for my services in all namespaces?

I already added the annotation sidecar.opentelemetry.io/inject: 'true' to the Pod, but it seems the sidecar can only be injected into the pod within the same namespace as the OpenTelemetryCollector manifest (tested).

Do I need to add any other annotation for the collector sidecar to be injected into the pod in the other namespace? 

Or the only current workaround is 1 OpenTelemetryCollector  : 1 namespace?

Thanks in advance!

**Comment by pavolloffay** [comment] 2022-12-01 14:39
This is a duplicate of https://github.com/open-telemetry/opentelemetry-operator/issues/199

**Closed by pavolloffay** 2022-12-01 14:39 UTC

**Comment by LinuxAd** [comment] 2022-12-12 17:42
I think this issue is related to #199, but the reason why this isn't currently available isn't clear from reading through that issue.

Looking at the linked MR from the issue takes you to this comment, which is the reason why this feature isn't currently supported.

https://github.com/open-telemetry/opentelemetry-operator/pull/889/files#r886838314
