### ISSUE TITLE
SqlClient trace disappear after we upgrade opentelemetry-operator to the latest version 

### ISSUE THREAD

**Issue by sr185436** [open-telemetry/opentelemetry-operator#1343] opened 2022-12-27 10:16 UTC
Today we upgrade to the latest version of opentelemetry-operator and we suddenly saw that all SqlClient trace disappear.

Hope to get some guidelines how to enable it in the new version.

thanks

**Comment by Kielek** [comment] 2022-12-27 11:26
What will be needed to help:

- operator version
- .NET version of instrumented applications
- logs from the OpenTelemetry .NET Automatic Istrumentation. Typically stored by operator under `/var/log/opentelemetry/dotnet`

BTW the latest operator is using OpenTelemetry .NET Automatic Istrumentation v0.5.0. Please check changelog if you are affected by this https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/CHANGELOG.md#050

**Comment by sr185436** [comment] 2022-12-27 11:45
i wrote i using now the latest version...
i not need to attach logs we don't get errors :) as i wrote here in the latest version of opentelemetry-operator we suddenly saw that all SqlClient trace disappear.

Hope to get some guidelines how to enable it in the new version.

**Comment by Kielek** [comment] 2022-12-27 12:06
I will ask once more time for
- .NET version of instrumented applications
- logs from the OpenTelemetry .NET Automatic Istrumentation. Typically stored by operator under `/var/log/opentelemetry/dotnet` - should contains a lot of interesting information, especially env. vars. and library versions loaded by the process. Especially if you enable debug log.

 Do you able to create minimal repro application? I am not telling that there is no issue, but I do not see any obvious thing which could leads to fail.

Sql Instrumentation for .NET process is enabled by default if `Microsoft.Data.SqlClient` or `System.Data` (only on .NET Framework) is loaded.

**Comment by pellared** [comment] 2022-12-29 10:54
It might be a bug in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/tree/v0.5.0

Can you please prepare accurate repro steps? Preferably source code of an application together with scripts/configuration that is not working. Of course please make sure to remove any sensitive data and try to make it as minimal as possible.

**Comment by sr185436** [comment] 2022-12-29 11:52
> It might be a bug in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/tree/v0.5.0
> 
> Can you please prepare accurate repro steps? Preferably source code of an application together with scripts/configuration that is not working. Of course please make sure to remove any sensitive data and try to make it as minimal as possible.

you can see all in https://github.com/open-telemetry/opentelemetry-dotnet/issues/4049

**Comment by pellared** [comment] 2022-12-29 12:03
I cannot find the repro steps.

**Comment by sr185436** [comment] 2022-12-29 12:39
here you can see all -> https://github.com/open-telemetry/opentelemetry-operator/issues/1341

1. We install the latest version of the Operator v0.66.0.
2. We using .NET version 6
3. SqlClient trace not showing after upgrade opentelemetry-operator to v0.66.0.

**Comment by pellared** [comment] 2022-12-29 12:50
Unfortunately, this is not enough for us to reproduce the error. We need some code and configuration that shows how you are using SQL Client so that it is not working as expected. 

It is possible (but I doubt it) that we could also find the problem if you share the logs as requested [here](https://github.com/open-telemetry/opentelemetry-operator/issues/1343#issuecomment-1365832871).

**Comment by sr185436** [comment] 2022-12-29 13:10
we use same code in the latest version of the Operator is not work when we remove the Operator and install the prev version all working well we don't change nothing only uninstall your Operator and install again another version!

**Comment by pellared** [comment] 2022-12-29 14:15
We are unable to reproduce with provided information. Are you able to modify https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/tree/main/test/test-applications/integrations/TestApplication.SqlClient test application so that it fails?

**Comment by swiatekm-sumo** [comment] 2023-08-01 10:44
I'm closing this due to lack of recent communication from the issue author. @sr185436 please feel free to reopen if you'd like to continue the conversation.

**Closed by swiatekm-sumo** 2023-08-01 10:44 UTC
Labels: bug, area:auto-instrumentation, auto-instrumentation:dotnet
