### ISSUE TITLE
On Openshift - Error "failed calling webhook 

### ISSUE THREAD

**Issue by Mariusko82** [open-telemetry/opentelemetry-operator#310] opened 2021-06-10 08:22 UTC
When I try to deploy/create instance of OpenTelemetryCollector I got this error:
 
Top of Form
Error
Error "failed calling webhook "mopentelemetrycollector.kb.io": Post https://opentelemetry-operator-controller-manager-service.acn-dev02.svc:443/mutate-opentelemetry-io-v1alpha1-opentelemetrycollector?timeout=10s: dial tcp 10.131.4.237:443: connect: connection refused" for field "undefined".
CreateCancel
Bottom of Form

**Comment by jpkrohling** [comment] 2021-06-10 09:03
Could you please share the steps to reproduce? Make sure to include the versions of the components you are using and how you are provisioning the operator.

**Comment by Mariusko82** [comment] 2021-06-13 08:12
We use ocp Client Version: openshift-clients-4.5.0-202006231303.p0-18-g6082e941e
Kubernetes Version: v1.18.3+fa69cae

operator version is opentelemetry-operator.v0.17.1

When I try to create OpenTelemetryCollector I got this error:

![image](https://user-images.githubusercontent.com/46222068/121800008-b957cb80-cc2f-11eb-97a0-5dfd0c42e27d.png)


An error occurred
Error "failed calling webhook "mopentelemetrycollector.kb.io": Post https://opentelemetry-operator-controller-manager-service.acn-dev02.svc:443/mutate-opentelemetry-io-v1alpha1-opentelemetrycollector?timeout=10s: dial tcp 10.130.8.24:443: connect: connection refused" for field "undefined".


My yaml is : 

apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetrycollector-sample
  namespace: acn-dev02
spec:
  config: |
    receivers:
      jaeger:
        protocols: 
          grpc:

    processors:
      queued_retry:

    exporters:
      logging:

    service:
      pipelines:
        traces:
          receivers: [jaeger]
          processors: [queued_retry]
          exporters: [logging]

**Comment by jpkrohling** [comment] 2021-06-24 08:53
Could you please share the steps to reproduce? For instance, how did you install the operator? Was it via OLM, or was it by installing the YAML from this repository? Any logs from the operator itself?

**Comment by Mariusko82** [comment] 2021-06-29 13:19
I found the issue - I had to edit target  port  of service opentelemetry-operator-controller-manager-service from 443 to 9443.

**Comment by jpkrohling** [comment] 2021-06-30 09:12
Is it a problem that we should be fixing on our side? Or was it due to a customization on your side?

**Comment by Mariusko82** [comment] 2021-07-28 08:02
I think problem is on side of opentelemetry operator. I have just found out that that targetPort was set automatically to wrong value 443. I had to make command to change it:

oc patch svc opentelemetry-operator-controller-manager-service -p '{"spec": {"ports": [{"name": "443","port": 443,"protocol": "TCP","targetPort": 9443}]}}'

**Comment by jpkrohling** [comment] 2021-07-29 13:16
Interesting. Are you able to reproduce it with a fresh OpenShift cluster, such as one provisioned via crc?

**Comment by pavolloffay** [comment] 2022-01-17 10:28
I am closing this as it seems like a stalled issue. 

If the problem is still relevant please re-open.

**Closed by pavolloffay** 2022-01-17 10:28 UTC
Labels: needs-info
