### ISSUE TITLE
Error creating a collector pod when specifying prometheus labeldrop actions

### ISSUE THREAD

**Issue by jacobwalters** [open-telemetry/opentelemetry-operator#958] opened 2022-05-31 19:43 UTC
**Describe the bug**
I am seeing this error 

```2022/05/31 17:54:37 application run finished with error: failed to get config: cannot unmarshal the configuration: error reading receivers configuration for "prometheus": prometheus receiver failed to unmarshal yaml to prometheus config: labeldrop action requires only 'regex', and no other fields```

This is happening when I am loading valid prometheus configurations into the opentelemetrycollector resource.

I am specifying the label drop actions like this.

```
metric_relabel_configs:
- regex: (.*id)
  action: labeldrop
```

The operator is creating a configmap called adot-collector where the labeldrop actions are transformed into this

```
metric_relabel_configs:
- separator: ;
  regex: (.*id)
  replacement: $1
  action: labeldrop
```

Compared to how I defined this, the operator is adding the fields "replacement", and "separator". These fields the operator is adding is causing the error in the logs above.

I was able to fix this issue by removing the label drop commands from my config and redeploying.

**Steps to reproduce**

Create a opentelemetrycollector object in statefulset mode with the targetAllocator enabled. configure the prometheus receiver to scrape a prometheus endpoint and use the metric_relabel_config field to drop a label. Observe the creation of the collector pod and the configmap generated by the operator. 

**What did you expect to see?**

I expected to see the opentelemetry-operator crate a collector pod successfully.
**What did you see instead?**
I saw that the opentelemetry-operator created the pod Adot-collecotr-0. It was in a crashback loop. I looked at the logs and saw this message
```
2022/05/31 17:54:37 application run finished with error: failed to get config: cannot unmarshal the configuration: error reading receivers configuration for "prometheus": prometheus receiver failed to unmarshal yaml to prometheus config: labeldrop action requires only 'regex', and no other fields
```
When i looked at eh configmap created by the operator. The labeldrop action had additional keys ("replacement", "seperator") that I had not added.

**What version did you use?**

Version: (e.g., `v0.4.0`, `1eb551b`, etc)
the opentelemetry helm charts. opentelemetry-collector-0.17.0

**What config did you use?**

```
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: adot
  namespace: opentelemetry
  labels:
    app: opentelemetry-operator
spec:
  image: "aws-otel-collector:0.17.0"
  mode: statefulset
  serviceAccount: generic-collector
  targetAllocator:
    enabled: true
    image: target-allocator:0.1.0
  resources:
    requests:
      cpu: 1
      memory: 6G
    limits:
      cpu: 1
      memory: 6G
  volumeMounts:
  - name: etcd-secrets
    mountPath: /etc/prometheus/secrets/kube-etcd-client-certs
  volumes: 
  - name: etcd-secrets
    secret:
      defaultMode: 420
      optional: true
      secretName: cilium-etcd-secrets
  volumeClaimTemplates:
  - metadata:
      name: shard-volume
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: ebs-all-zones
      resources:
        requests:
          storage: 1Gi
  config: |
    receivers:
      prometheus:
        config:
          global:
            scrape_interval: 60s
            scrape_timeout: 10s
          scrape_configs:
          - job_name: kubelet
            honor_labels: false
            honor_timestamps: false
            metrics_path: /metrics
            scheme: https
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            tls_config:
              insecure_skip_verify: true
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                names:
                - kube-system
            relabel_configs:
            - action: keep
              regex: kubelet
              source_labels: [__meta_kubernetes_endpoints_name]
            - action: keep
              regex: https-metrics
              source_labels: [__meta_kubernetes_endpoint_port_name]
            metric_relabel_configs:
            - action: labeldrop
              regex: (.*id)
    exporters:
      awsprometheusremotewrite:
        timeout: 30s
        endpoint: https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-dummy-value/api/v1/remote_write
        aws_auth:
          region: "us-east-1"
          service: "aps"
        external_labels:
          clusterId: clusterId
          cluster: clustername
          env: poc
          __replica__: ${POD_NAME}
      logging:
        loglevel: warn
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 70
        spike_limit_percentage: 20
      batch:
      batch/2:
        timeout: 10s
        send_batch_size: 10000
        send_batch_max_size: 12000
    extensions:
      health_check:
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679
    service:
      extensions: [pprof, zpages, health_check]
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [memory_limiter, batch]
          exporters: [logging, awsprometheusremotewrite]
```

**Environment**
EKS 1.20 cluster

**Additional context**

**Comment by anushavidya** [comment] 2023-03-15 01:20
I am seeing the same issue when specifying a valid `labelmap` action in the scrape job.

**Comment by utr1903** [comment] 2023-03-22 21:36
@anunarapureddy I am also having the same issue with labelmap

**Comment by alolita** [comment] 2023-03-28 00:21
@open-telemetry/operator-maintainers can you please reassign this issue to @anunarapureddy Thanks!

**Comment by Nitesh-vaidyanath** [comment] 2023-03-29 11:33
Even I am able to reproduce for version opentelmetry operator version v0.73.0

`Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'receivers': error reading configuration for "prometheus": prometheus receiver failed to unmarshal yaml to prometheus config: "" is invalid 'replacement' for labelmap action
2023/03/29 11:25:12 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'receivers': error reading configuration for "prometheus": prometheus receiver failed to unmarshal yaml to prometheus config: "" is invalid 'replacement' for labelmap action`

**Comment by Nitesh-vaidyanath** [comment] 2023-03-29 16:06
Looks like I found issue here  https://github.com/prometheus/prometheus/blob/main/model/relabel/relabel.go. 

          DefaultRelabelConfig = Config{
		          Action:      Replace,
		          Separator:   ";",
		          Regex:       MustNewRegexp("(.*)"),
		          Replacement: "$1",
	          }

            func (c *Config) UnmarshalYAML(unmarshal func(interface{}) error) error {
	            *c = DefaultRelabelConfig
	
metric_relabel_configs expects only regex field but actual config is overwritten by DefaultRelabelConfig which is returning error from below if condition.

            metric_relabel_configs:
            - action: labeldrop
              regex: (.*id)
              
	if c.Action == LabelDrop || c.Action == LabelKeep {
		if c.SourceLabels != nil ||
			c.TargetLabel != DefaultRelabelConfig.TargetLabel ||
			c.Modulus != DefaultRelabelConfig.Modulus ||
			c.Separator != DefaultRelabelConfig.Separator ||
			c.Replacement != DefaultRelabelConfig.Replacement {
			return fmt.Errorf("%s action requires only 'regex', and no other fields", c.Action)
		}
	}

**Comment by Nitesh-vaidyanath** [comment] 2023-03-29 16:13
> Looks like I found issue here https://github.com/prometheus/prometheus/blob/main/model/relabel/relabel.go.
> 
> ```
>       DefaultRelabelConfig = Config{
> 	          Action:      Replace,
> 	          Separator:   ";",
> 	          Regex:       MustNewRegexp("(.*)"),
> 	          Replacement: "$1",
>           }
> 
>         func (c *Config) UnmarshalYAML(unmarshal func(interface{}) error) error {
>             *c = DefaultRelabelConfig
> ```
> 
> metric_relabel_configs expects only regex field but actual config is overwritten by DefaultRelabelConfig which is returning error from below if condition.
> 
> ```
>         metric_relabel_configs:
>         - action: labeldrop
>           regex: (.*id)
>           
> if c.Action == LabelDrop || c.Action == LabelKeep {
> 	if c.SourceLabels != nil ||
> 		c.TargetLabel != DefaultRelabelConfig.TargetLabel ||
> 		c.Modulus != DefaultRelabelConfig.Modulus ||
> 		c.Separator != DefaultRelabelConfig.Separator ||
> 		c.Replacement != DefaultRelabelConfig.Replacement {
> 		return fmt.Errorf("%s action requires only 'regex', and no other fields", c.Action)
> 	}
> }
> ```



> https://github.com/prometheus/prometheus/blob/main/model/relabel/relabel.go

<img width="595" alt="Screenshot 2023-03-30 at 12 12 06 AM" src="https://user-images.githubusercontent.com/12709763/228601363-88e5a85d-13d1-4422-82fd-9211292f8dd6.png">
<img width="857" alt="Screenshot 2023-03-30 at 12 12 13 AM" src="https://user-images.githubusercontent.com/12709763/228601375-e9518d34-fa37-4d93-95e8-937a841dc875.png">
<img width="669" alt="Screenshot 2023-03-30 at 12 12 24 AM" src="https://user-images.githubusercontent.com/12709763/228601383-cd5a3398-7bd7-49ee-8984-b716356917da.png">

**Comment by matej-g** [comment] 2023-04-19 11:23
Looks like the cause of the issue is clear. Is anyone working on a fix?

**Comment by jaronoff97** [comment] 2023-04-19 12:39
@matej-g I believe @anunarapureddy is working on a fix, we were having a discussion in [the slack](https://cloud-native.slack.com/archives/C033BJ8BASU/p1680552719300249) about it

**Comment by jaronoff97** [comment] 2023-10-24 16:46
This should have been resolved by https://github.com/open-telemetry/opentelemetry-operator/pull/1712 please let me know if you are still experiencing issues on the latest versions.

**Closed by jaronoff97** 2023-10-24 16:46 UTC
Labels: bug, area:target-allocator

**Comment by OzoneChris** [comment] 2025-04-07 03:28
There is a `labeldrop` example in the promtail-lambda docs [here](https://grafana.com/docs/loki/latest/send-data/lambda-promtail/#relabeling-configuration) which gives a `invalid relabel config: labeldrop action requires only 'regex', and no other fields` error, despite passing in a config with only regex and action. Could this be the same thing?

**Comment by OzoneChris** [comment] 2025-04-08 01:53
Its not pressing, as I can do the same thing with the `DROP_LABELS` var. But I passed the example exactly per the docs and the error bought me here, so I thought it helpful to drop a note. 

```json
[
    {
      "regex": "__aws_.*",
      "action": "labeldrop"
    }
  ]
