### ISSUE TITLE
Failed to select an OpenTelemetry Collector instance for pod's sidecar 

### ISSUE THREAD

**Issue by gerijani** [open-telemetry/opentelemetry-operator#2558] opened 2024-01-19 23:03 UTC
### Component(s)

operator

### Describe the issue you're reporting

We'd deployed recently OT into our AKS cluster and are now trying to use auto instrumentation but the operator always throws the below error:

```
{"level":"error","ts":"2024-01-19T10:32:29Z","msg":"failed to select an OpenTelemetry Collector instance for this pod's sidecar",
"namespace":"opentelemetry",
"name":"platform-samples-api-2",
"error":"no OpenTelemetry Collector instances available",
"stacktrace":
"github.com/open-telemetry/opentelemetry-operator/pkg/sidecar.(*sidecarPodMutator).Mutate
/home/runner/work/opentelemetry-operator/opentelemetry-operator/pkg/sidecar/podmutator.go:84\ngithub.com/open-telemetry/opentelemetry-operator/internal/webhook/podmutation.(*podMutationWebhook).Handle
/home/runner/work/opentelemetry-operator/opentelemetry-operator/internal/webhook/podmutation/webhookhandler.go:92\nsigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/webhook/admission/webhook.go:169\nsigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/webhook/admission/http.go:98\nsigs.k8s.io/controller-runtime/pkg/webhook/internal/metrics.InstrumentedHook.InstrumentHandlerInFlight.func1
/home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.18.0/prometheus/promhttp/instrument_server.go:60\nnet/http.HandlerFunc.ServeHTTP
/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1
/home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.18.0/prometheus/promhttp/instrument_server.go:147\nnet/http.HandlerFunc.ServeHTTP
/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2
/home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.18.0/prometheus/promhttp/instrument_server.go:109\nnet/http.HandlerFunc.ServeHTTP
/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136\nnet/http.(*ServeMux).ServeHTTP
/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2514\nnet/http.serverHandler.ServeHTTP
/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2938\nnet/http.(*conn).serve
/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2009"}
```

We used HELM chart 0.45.2 for the deployment with operator version 0.92.0. As we are in AKS we modified clusterrole.yaml template as  this was also needed, and added:
```
- apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - get
      - list
      - watch
```
Value file has the only modification as below:
```
autoInstrumentationImage:
  python:
     repository: "otel/autoinstrumentation-python"
        tag: ""
  dotnet:
     repository: "otel/autoinstrumentation-dotnet"
        tag: ""

```
And also deployed a collector-contrib instance with HELM using [chart 0.78.0 and appVersion 0.92.0](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/Chart.yaml) as statefulset.
Currently the whole deployment looks like this:
```
$ kubectl get all
NAME                            READY   STATUS    RESTARTS   AGE
pod/collector-0                 1/1     Running   0          29s
pod/operator-65c799c7c8-kwqtz   2/2     Running   0          2m52s

NAME                                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
service/collector                      ClusterIP   172.32.63.130   <none>        4317/TCP,4318/TCP   3d7h
service/operator                       ClusterIP   172.32.49.255   <none>        8443/TCP,8080/TCP   2m52s
service/operator-webhook               ClusterIP   172.32.36.17    <none>        443/TCP             2m52s
service/platform-samples-api-service   ClusterIP   172.32.18.119   <none>        80/TCP,443/TCP      13h

NAME                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/operator   1/1     1            1           2m53s

NAME                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/operator-65c799c7c8   1         1         1       2m53s

NAME                         READY   AGE
statefulset.apps/collector   1/1     3d7h

```
And with the sample application has the annotation sidecar.opentelemetry.io/inject: 'true' yet we get the above error.

**Comment by gerijani** [comment] 2024-01-25 08:57
@TylerHelmuth thanks for the confirmation. 
Does it also mean that code injection for .Net/Python./.. instrumentation is only works in sidecar mode?

**Comment by TylerHelmuth** [comment] 2024-01-25 15:57
No, all the Operators auto-instrumentation inject uses initContainers except for Go.  But the error message you posted is unrelated to auto-instrumentation, it is related to the OpenTelemetry Collector custom resource.

**Comment by pavolloffay** [comment] 2024-01-26 09:27
This is expected behavior, the collector CR with sidecar mode is missing in the cluster. 

There is no actionable agenda for us in this ticket. Closing. 

This was a duplicate of #2548.

**Closed by pavolloffay** 2024-01-26 09:27 UTC
Labels: area:collector
