### ISSUE TITLE
Update Community OpenTelemetry Operator on Openshift/OKD to v0.34.0

### ISSUE THREAD

**Issue by RishiRavikumar** [open-telemetry/opentelemetry-operator#433] opened 2021-09-17 04:33 UTC
Hi,

The Community OpenTelemetry Operator on Openshift/OKD shows the latest version as v0.33.0. We require v0.34.0 for our requirements, and are looking for the update on the Operator Hub on the OKD platform.  Please let us know if there's a update lined up for the same

Thanks

**Comment by jpkrohling** [comment] 2021-09-17 10:31
cc @pavolloffay

**Comment by RishiRavikumar** [comment] 2021-10-05 05:25
@jpkrohling @pavolloffay 
Hi,
Any updates on this?

**Comment by jpkrohling** [comment] 2021-10-05 07:50
I do not have any updates. @pavolloffay, are you planning on working on this?

**Comment by pavolloffay** [comment] 2021-10-11 12:58
I see that 0.34.0 and 0.35.0 were released by @jpkrohling. 

Updating the community operators is part of the release process https://github.com/open-telemetry/opentelemetry-operator/blob/main/RELEASE.md#release-instructions.

**Comment by jpkrohling** [comment] 2021-10-11 13:08
> Go ahead @jpkrohling if you have free cycles.

I don't currently have.

> Updating the community operators is part of the release process

Good point, I'll remove it, as it's not a requirement for releases.

**Comment by rkukura** [comment] 2021-11-08 15:09
I updated operator hub to 1.37.1 for Kubernetes, but ran into an issue with 1.37.1 (and also 1.33.0) on OpenShift 4.9 where the opentelemetry-operator-controller-manager exits with an error in client-go and keeps getting restarted, then fails to uninstall cleanly. I see the same behavior on Kubernetes 1.22. I'm going to move to testing the just-released 1.38.0 on both today, and updating operator hub if the issue is resolved.

**Comment by rkukura** [comment] 2021-11-11 21:30
OpenShift PR: https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/430 (note CI is currently broken, but has passed all tests)
Kubernetes PR: https://github.com/k8s-operatorhub/community-operators/pull/396

We should be able to close this once those merge.

**Comment by rkukura** [comment] 2021-11-12 19:44
Both the OpenShift and Kubernetes operator hubs have now been updated to 0.38.0, with the fixed CRD from https://github.com/open-telemetry/opentelemetry-operator/pull/521, so this issue can now be closed.

**Closed** 2021-11-17 09:52 UTC
Labels: enhancement, good first issue, help wanted, hacktoberfest
