### ISSUE TITLE
Add the ability to assign annotations to service account otel-collector

### ISSUE THREAD

**Issue by paco-sisutech** [open-telemetry/opentelemetry-operator#2244] opened 2023-10-18 11:33 UTC
### Component(s)

collector

### Is your feature request related to a problem? Please describe.

I'm trying to get opentelemetry collector running in GKE to export data to google cloud trace as explained here:
https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/kustomize/components/google-cloud-operations#workload-identity
So, I need to annotate the service account generated by the collector (otel-collector) but it gets constantly overwritten. Is it there some way to make it work adding some section in the collector.yaml file so it would persist the annotation?
I'm using the opentelemetry operator and the CR of the collector to generate it

Changing the serviceAccount to my own service account still generates the service otel-collector

### Describe the solution you'd like

I would like the possibility to add annotations to the service account otel-collector generated by the operator

### Describe alternatives you've considered

Add my own service account which would be used by the collector

**Comment by pavolloffay** [comment] 2023-10-18 15:35
Duplicate of https://github.com/open-telemetry/opentelemetry-operator/issues/2227

As it was mentioned in the original ticket. The custom SA can be provided in the CR. If the operator creates SA anyways it's a bug and should be fixed.

**Comment by pavolloffay** [comment] 2023-10-18 15:39
Also as you can see here https://github.com/opentelemetrybot/opentelemetry-operator/blob/cc88d1a82d00e7cb2055faff360f71f2e2716cb3/internal/manifests/targetallocator/serviceaccount.go#L46 

The OTEL col CR annotations are propagated to the created SA.

**Comment by paco-sisutech** [comment] 2023-10-19 06:09
Sorry, I couldnt reopen the previous issue so I have to create this one. So far my work around is that I give the annotation to the Collector CR and it propagate the annotation to all the resources under it, but it would be good to not create the service account if I assign one for less confusion

**Comment by jaronoff97** [comment] 2023-11-28 23:03
this should be resolved by #2378

**Closed by jaronoff97** 2023-11-28 23:03 UTC
Labels: bug, enhancement, area:collector
