### ISSUE TITLE
Auto-update Java agent workflow is failing

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-operator#1922] opened 2023-07-13 15:54 UTC
https://github.com/open-telemetry/opentelemetry-operator/actions/workflows/auto-update-java-agent.yaml

> remote: error: GH006: Protected branch update failed for refs/heads/opentelemetrybot/update-opentelemetry-java-agent-to-1.28.0.

Can you open a repo maintenance request in the community repo to override default branch protections for `opentelemetrybot/**/**`, same as:

https://github.com/open-telemetry/community/blob/b471348f9c3b85dc5824c8c313bcca4c091773be/docs/how-to-configure-new-repository.md?plain=1#L91

**Comment by TylerHelmuth** [comment] 2023-07-13 18:10
Duplicate of https://github.com/open-telemetry/opentelemetry-operator/issues/1917. 

We'll open that request

**Closed** 2023-07-13 18:19 UTC
