### ISSUE TITLE
Publish the operator bundle container images

### ISSUE THREAD

**Issue by iblancasa** [open-telemetry/opentelemetry-operator#1879] opened 2023-06-28 16:26 UTC
Currently, the GitHub Workflows are building and publishing the [following images](https://github.com/orgs/open-telemetry/packages?repo_name=opentelemetry-operator):
- `opentelemetry-operator`
- `autoinstrumentation-java`
- `autoinstrumentation-dotnet`
- `autoinstrumentation-python`
- `autoinstrumentation-nodejs`
- `target-allocator`
- `autoinstrumentation-apache-httpd`
- `operator-opamp-bridge`

But not the `opentelemetry-operator-bundle`. This task is to build and publish the image as part of the GitHub Actions Workflows.

**Comment by iblancasa** [comment] 2023-06-30 13:56
Related #1877

**Comment by pavolloffay** [comment] 2023-06-30 14:14
This seems to be a duplicate of https://github.com/open-telemetry/opentelemetry-operator/issues/1823. Please re-open if it is not the case.

**Closed** 2023-07-11 14:13 UTC
