### ISSUE TITLE
Operator deployment fails with ImagePullBackOff

### ISSUE THREAD

**Issue by kaskavalci** [open-telemetry/opentelemetry-operator#266] opened 2021-05-06 09:26 UTC
```
 Back-off pulling image "quay.io/opentelemetry/opentelemetry-operator:0.24.0": ImagePullBackOff 
```

It seems [operator image](https://quay.io/repository/opentelemetry/opentelemetry-operator?tab=tags) v0.24.0 is pushed with `v` prefix but operator refers it without the prefix `0.24.0`.

Workaround:

Update deployment `opentelemetry-operator-controller-manager` to use image tag `v0.24.0` in manager container.

**Comment by jpkrohling** [comment] 2021-05-06 09:54
Thanks for reporting this. This is a duplicate of #259 and should be fixed for the next release. In any case, I just pushed a new tag with the value that the published manifest expects: `quay.io/opentelemetry/opentelemetry-operator:0.24.0`. It should start working again without changes.

**Closed by jpkrohling** 2021-05-06 09:54 UTC
